name: Python-debug
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 9 * * *'
jobs:
  job_update:
    name: Python Crawler
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: '指定python环境'
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    - name: run py
      run: python run.py
    - name: "检查目录"
      run: ls
    - name: update file
      run: |
         git config --local user.email "2567810193@qq.com"
         git config --local user.name "Mnaisuka"
         git pull
         git add debug.text
         git commit -m "update debug.text"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.my_token }}
         branch: main