name: Python-debug

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "0 17 * * *" # 每天 UTC 时间 17:00 执行一次

jobs:
  job_update:
    name: Python Crawler
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 指定 Python 环境
        uses: actions/setup-python@v3
        with:
          python-version: "3.11.9"

      - name: 安装依赖
        run: pip install requests

      - name: 检查目录
        run: ls

      - name: TLD 自动更新
        env:
          GH_TOKEN: ${{ secrets.BIG_TOKEN }}
        run: python thelongdark/index.py

      - name: 再次检查目录
        run: ls

      - name: 提交并推送更新（仅在有更改时）
        run: |
          git config --local user.email "2567810193@qq.com"
          git config --local user.name "Mnaisuka"
          git pull
          git add thelongdark/*

          # 判断是否有变更
          if git diff --cached --quiet; then
            echo "无变更内容，跳过提交与推送。"
          else
            git commit -m "update"
            git push https://x-access-token:${{ secrets.MY_TOKEN }}@github.com/${{ github.repository }}.git main
          fi

  deploy:
    name: Deploy GitHub Pages
    needs: job_update
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: 拉取最新内容
        run: |
          git config --local user.email "2567810193@qq.com"
          git config --local user.name "Mnaisuka"
          git pull

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
